---
- name: Docker installeren
  hosts: all
  become: yes
  tasks:
    - name: Docker dependencies installeren
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Docker GPG key toevoegen
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Docker repository toevoegen
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: APT package cache bijwerken
      apt:
        update_cache: yes

    - name: Docker installeren
      apt:
        name: docker-ce
        state: present

    - name: Docker service starten en inschakelen
      service:
        name: docker
        state: started
        enabled: yes
#installatie van de pakketten door Docker
#GPG-Sleutel van Docker toegevoegd
#Docker-apt-rep toegevoegd
#bijwerken APT-pakketcache
#installatie van Docker 
#start en enable van Docker-service

